config/routes.rb
Rails.application.routes.draw do


  root 'home#index'

  mount Ckeditor::Engine => '/ckeditor'

  get 'service/:url' => 'pages#show'
  get 'admin', to: redirect('/administraccion/login')
  get 'freelance', to: redirect('/freelance/login')
  get 'login', to: redirect('/usuario/iniciar_sesion')

  resources :forms, :form_answers, :pages

  devise_for :admins, path: 'administraccion', path_names: {sign_in: 'login', sign_out: 'cerrar_session'}, :skip =>[:registrations], controllers: {
    sessions: 'admins/sessions'
  }
  
  devise_for :users, path: 'usuario', path_names: {sign_in: 'iniciar_sesion', sign_up: 'registrate'}, controllers: {
    sessions: 'users/sessions'
  }

  devise_for :freelances, path: 'freelance', path_names: {sign_in: 'login'}, :skip =>[:registrations], controllers: {
    sessions: 'freelances/sessions'
  }


  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    resources :roles, :f_roles, :services, :pages, :deliveries, :admins, :freelances, :form_builds, :form_questions
    scope '/service' do
      resources :categories, :bundles
    end
  end

  namespace :freelance do
    get 'dashboard' => 'dashboard#index'
  end
 
end

app/models/admin.rb
class Admin < ActiveRecord::Base
	belongs_to :role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", cover: "160x160>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/bundle.rb
class Bundle < ActiveRecord::Base
	has_and_belongs_to_many :services
  belongs_to :page
  before_save :capitalize_name
	 has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\Z/
  has_attached_file :imghover, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :imghover, content_type: /\Aimage\/.*\Z/

	protected
	def capitalize_name
      self.name = self.name.capitalize
    end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :services
	before_save :capitalize_name

	protected
	def capitalize_name
      self.name = self.name.capitalize
    end
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
	belongs_to :service
end

app/models/f_role.rb
class FRole < ActiveRecord::Base
	has_many :freelances
	before_save :capitalize_name

	protected
	def capitalize_name
      self.name = self.name.capitalize
    end
end

app/models/form.rb
class Form < ActiveRecord::Base
  belongs_to :form_build
  belongs_to :status_order
  has_many :answers, class_name: 'FormAnswer'
	accepts_nested_attributes_for :answers, allow_destroy: true

	before_save :status

	protected
	def status
			status_name = StatusOrder.find_by_name('Pendiente')
      self.status_order_id = status_name.id
    end
end

app/models/form_answer.rb
class FormAnswer < ActiveRecord::Base
  belongs_to :form
end

app/models/form_build.rb
class FormBuild < ActiveRecord::Base
	belongs_to :service
	has_many :questions, class_name: 'FormQuestion'
	accepts_nested_attributes_for :questions, allow_destroy: true
end

app/models/form_question.rb
class FormQuestion < ActiveRecord::Base
  belongs_to :form_build
end

app/models/freelance.rb
class Freelance < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable :timeoutable and :omniauthable
  belongs_to :level
  belongs_to :f_role
  after_save :create_wallet
  devise :database_authenticatable, :recoverable, :registerable,
    :rememberable, :trackable, :validatable
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", cover: "160x160>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :gender, :name, :last_name, :f_role_id, presence: true

  def create_wallet
  	id = self.id
  	if !Wallet.find_by_freelance_id(id)
	  	wallet = Wallet.new
	  	wallet.money = 0
	  	wallet.freelance_id = id
		  wallet.save
  	end
  end

end

app/models/level.rb
class Level < ActiveRecord::Base
	has_many :freelances
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :service
  belongs_to :bundle
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :admins
	before_save :capitalize_name

	protected
	def capitalize_name
      self.name = self.name.capitalize
    end
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :category
  belongs_to :page
  has_many :form_builds
  has_and_belongs_to_many :bundles
  has_many :deliveries
  accepts_nested_attributes_for :deliveries, allow_destroy: true
  
	before_save :capitalize_name
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\Z/
  has_attached_file :imghover, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :imghover, content_type: /\Aimage\/.*\Z/
  #has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "0.png"
  #validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	protected
	def capitalize_name
      self.name = self.name.capitalize
    end
end

app/models/status_order.rb
class StatusOrder < ActiveRecord::Base
	has_many :forms
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/wallet.rb
class Wallet < ActiveRecord::Base
	belongs_to :freelance
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	@pagesServices = Page.where(visibility: true).where.not(service_id: nil)
  	@pagesBundles = Page.where(visibility: true).where.not(bundle_id: nil)

  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def show
		@page = Page.find_by_url(params[:url])
    @form = FormQuestion.where(form_build_id = @page.form_build_id)
		@formDelivery = FormBuild.find_by_id(@page.form_build_id)
		@answer = Form.new
    @answer.answers.build

  end

  def create
    @answer = Form.new(form_params)
    if @answer.save
      redirect_to root_path, notice: 'Survey was successfully created.'
    else
      puts "----------------" + @answer.form_build_id
    end
  end

  private

    def form_params
      params.require(:form).permit(:form_build_id, :status_order_id, answers_attributes: [ :id, :content, :_destroy])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |question|
      render(association.to_s.singularize + "_fields", f: question)
    end
    link_to(name, '', class: "add_fields", data: { id: id, fields: fields.gsub("\n", "")})
  end
end

app/views/admin/pages/index.html.haml
%section.content-wrapper
  %section.content-header
    %h1 Todas las paginas
  %section.content
    .row
      .col-xs-12
        .box
          .box-body.table-responsive.no-padding
            %table.table.table-hover
              %tbody
                %tr
                  %th Titulo
                  %th Estado
                  %th Servicio
                  %th Paquete
                  %th Creado
                  %th Actualizado
                  %th{colspan: "2"} Acciones
              - @pages.each do |page|
                %tr
                  %td= page.title
                  - if page.visibility == true
                    %td{style: "color: #04A756;"} Activo
                  - else
                    %td{style: "color: #C82727;"} Desactivado
                  - if page.service.nil?
                    %td
                  - else
                    %td= page.service.name
                  - if page.bundle.nil?
                    %td
                  - else
                    %td= page.bundle.name
                  %td= page.created_at.httpdate.to_date
                  %td= page.updated_at.httpdate.to_date
                  %td
                    = link_to edit_admin_page_path(page) do
                      %i.fa.fa-edit
                  %td
                    = link_to admin_page_path(page), method: :delete, data: { confirm: 'Esta seguro?' } do
                      %i.fa.fa-remove{style: "color: #B21919;"}

app/views/partials/admin/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <a href="index2.html" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>Trely</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>TRELY</b></span>
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- Messages: style can be found in dropdown.less-->
        <li class="dropdown messages-menu">
          <!-- Menu toggle button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-envelope-o"></i>
            <span class="label label-success">1</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 1 messages</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 200px;">
                <ul class="menu" style="overflow: hidden; width: 100%; height: 200px;">
                  <li><!-- start message -->
                    <a href="#">
                      <div class="pull-left">
                        <% if !current_admin.avatar.exists? %> 
                          <% if current_admin.gender.capitalize == "Masculino" %>
                            <%= image_tag "avatar5.png", class: "img-circle", alt: "User Image" %>
                          <% else %>
                            <%= image_tag "avatar2.png", class: "img-circle", alt: "User Image" %>
                          <% end %>
                        <% else %>
                          <%= image_tag current_admin.avatar.url(:cover), class: "img-circle", alt: "User Image" %>
                        <% end %>
                      </div>
                      <h4>
                        Support Team
                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                      </h4>
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li><!-- end message -->
                </ul>
                <div class="slimScrollBar" style="width: 3px; position: absolute; top: 69px; opacity: 0.4; display: none; border-radius: 7px; z-index: 99; right: 1px; height: 131.148px; background: rgb(0, 0, 0);">
                </div>
                <div class="slimScrollRail" style="width: 3px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; opacity: 0.2; z-index: 90; right: 1px; background: rgb(51, 51, 51);">
                </div>
              </div>
            </li>
            <li class="footer"><a href="#">See All Messages</a></li>
          </ul>
        </li><!-- /.messages-menu -->

        <!-- Notifications Menu -->
        <li class="dropdown notifications-menu">
          <!-- Menu toggle button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell-o"></i>
            <span class="label label-warning">1</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 1 notifications</li>
            <li>
              <!-- Inner Menu: contains the notifications -->
              <ul class="menu">
                <li><!-- start notification -->
                  <a href="#">
                    <i class="fa fa-users text-aqua"></i> 1 new members joined today
                  </a>
                </li><!-- end notification -->
              </ul>
            </li>
            <li class="footer"><a href="#">View all</a></li>
          </ul>
        </li>
        <!-- Tasks Menu -->
        <li class="dropdown tasks-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-flag-o"></i>
            <span class="label label-danger">1</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 1 tasks</li>
            <li>
              <!-- Inner menu: contains the tasks -->
              <ul class="menu">
                <li><!-- Task item -->
                  <a href="#">
                    <!-- Task title and progress text -->
                    <h3>
                      Design some buttons
                      <small class="pull-right">80%</small>
                    </h3>
                    <!-- The progress bar -->
                    <div class="progress xs">
                      <!-- Change the css width attribute to simulate progress -->
                      <div class="progress-bar progress-bar-aqua" style="width: 80%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">80% Complete</span>
                      </div>
                    </div>
                  </a>
                </li><!-- end task item -->
              </ul>
            </li>
            <li class="footer">
              <a href="#">View all tasks</a>
            </li>
          </ul>
        </li>
        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <% if !current_admin.avatar.exists? %>
              <% if current_admin.gender.capitalize == "Masculino" %>
                  <%= image_tag "avatar5.png", class: "user-image", alt: "User Image" %>
              <% else %>
                  <%= image_tag "avatar2.png", class: "user-image", alt: "User Image" %>
              <% end %>
            <% else %>
                <%= image_tag current_admin.avatar.url(:cover), class: "user-image", alt: "User Image" %>
            <% end %>
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs"><%= current_admin.name.capitalize %> <%= current_admin.last_name.capitalize %></span>
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
              <% if !current_admin.avatar.exists? %>
                <% if current_admin.gender.capitalize == "Masculino" %>
                    <%= image_tag "avatar5.png", class: "img-circle", alt: "User Image" %>
                <% else %>
                    <%= image_tag "avatar2.png", class: "img-circle", alt: "User Image" %>
                <% end %>
              <% else %>
                  <%= image_tag current_admin.avatar.url(:cover), class: "img-circle", alt: "User Image" %>
              <% end %>
              <p>
                <%= current_admin.name.capitalize %> <%= current_admin.last_name.capitalize %>
                <small><%= current_admin.role.name %></small>
              </p>
            </li>
            <!-- Menu Body -->
            <!--li class="user-body">
              <div class="col-xs-4 text-center">
                <a href="#">Followers</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Sales</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Friends</a>
              </div>
            </li-->
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <%= link_to('Cerrar sesion', destroy_admin_session_path, :method => :delete, class: "btn btn-sm btn-flat") %> 
              </div>
              <div class="pull-right">
                <%= link_to('Perfil', admin_admin_path(current_admin.id), class: "btn btn-sm btn-flat") %> 
              </div>
            </li>
          </ul>
        </li>
        <!-- Control Sidebar Toggle Button -->
        <!--li>
          <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
        </li-->
      </ul>
    </div>
  </nav>
</header>

app/views/partials/admin/_nav.html.erb
<aside class="main-sidebar">
<!-- sidebar: style can be found in sidebar.less -->
	<section class="sidebar">
	  <!-- Sidebar user panel (optional) -->
	  <div class="user-panel">
	    <div class="pull-left image">
	      <% if !current_admin.avatar.exists? %>
	        <% if current_admin.gender.capitalize == "Masculino" %>
	            <%= image_tag "avatar5.png", class: "img-circle", alt: "User Image" %>
	        <% else %>
	            <%= image_tag "avatar2.png", class: "img-circle", alt: "User Image" %>
	        <% end %>
	      <% else %>
	          <%= image_tag current_admin.avatar.url(:cover), class: "img-circle", alt: "User Image", style: "height: 45px !important;" %>
	      <% end %>
	    </div>
	    <div class="pull-left info">
	      <p><%= current_admin.name.capitalize %> <%= current_admin.last_name.capitalize %></p>
	      <!-- Status -->
	      <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
	    </div>
	  </div>
	  <!-- search form (Optional) -->
	  <!-- /.search form -->
	  <!-- Sidebar Menu -->
	  <ul class="sidebar-menu">
	    <!--li class="header">HEADER</li-->
	    <!-- Optionally, you can add icons to the links -->

	    <!-- nav 1 -->
	      <% if current_page?(admin_dashboard_path) %>
	        <li class="treeview active">
	      <%else%>
	        <li class="treeview">
	      <%end%>
	      <%= link_to admin_dashboard_path do %>
	        <i class="fa fa-circle-o"></i>
	        <span>Home</span>
	      <% end %>
	    </li>

	    <!-- nav 2 -->
	    <% if current_page?(admin_pages_path) or current_page?(new_admin_page_path) %>
	      <li class="treeview active">
	    <%else%>
	      <li class="treeview">
	    <%end%>
		      <a href="#">
			      <i class="fa fa-link"></i> 
			      <span>Paginas</span>
			      <i class="fa fa-angle-left pull-right"></i>
		      </a>
		      <ul class="treeview-menu menu-open" style="">
		      <% if current_page?(new_admin_page_path) %>
		      	<li class="active">
		      <%else%>
		        <li class="">
		      <%end%>
		        <%= link_to new_admin_page_path do %>
			        <i class="fa fa-circle-o"></i>
			        <span>Nuevo</span>
		        <% end %>
		        </li>
		        <% if current_page?(admin_pages_path) %>
		        	<li class="active">
		        <%else%>
		        	<li class="">
		        <%end%>
		        <%= link_to admin_pages_path do %>
			        <i class="fa fa-circle-o"></i>
			        <span>Todas las paginas</span>
		        <% end %>
		        </li>
		      </ul>
	    </li>

	    <!-- nav 3 -->
	    <% if current_page?(admin_categories_path) or current_page?(new_admin_category_path) or current_page?(admin_bundles_path) or current_page?(new_admin_bundle_path) or current_page?(admin_services_path) or current_page?(new_admin_service_path) %>
	    	<li class="treeview active">
	    <%else%>
	      <li class="treeview">
	    <%end%>
	      <a href="#">
	        <i class="fa fa-share"></i> 
	        <span>Servicios</span>
	        <i class="fa fa-angle-left pull-right"></i>
	      </a>
	      <ul class="treeview-menu menu-open" style="">
	        <% if current_page?(new_admin_service_path) %>
	          <li class="active">
	        <%else%>
	          <li class="">
	        <%end%>
	        <%= link_to new_admin_service_path do %>
	          <i class="fa fa-circle-o"></i>
	          <span>Nuevo</span>
	        <% end %>
	        </li>
	        <% if current_page?(admin_services_path) %>
	          <li class="active">
	        <%else%>
	          <li class="">
	        <%end%>
		        <%= link_to admin_services_path do %>
		          <i class="fa fa-circle-o"></i>
		          <span>Todos los servicios</span>
		        <% end %>
	        	</li>
	        <% if current_page?(admin_categories_path) or current_page?(new_admin_category_path) %>
	          <li class="active">
	        <%else%>
	          <li class="">
	        <%end%>
	          <a href="#">
		          <i class="fa fa-circle-o"></i>
		           <span>Categorias</span>
		           <i class="fa fa-angle-left pull-right"></i>
	          </a>
	          <ul class="treeview-menu menu-open" style="">
	            <% if current_page?(new_admin_category_path) %>
	              <li class="active">
	            <%else%>
	              <li class="">
	            <%end%>
	              <%= link_to new_admin_category_path do %>
	                <i class="fa fa-circle-o"></i>
	                <span>Nueva</span>
	              <% end %>
	            </li>
	            <% if current_page?(admin_categories_path) %>
	              <li class="active">
	            <%else%>
	              <li class="">
	            <%end%>
	              <%= link_to admin_categories_path do %>
	                <i class="fa fa-circle-o"></i>
	                <span>Todas las categorias</span>
	              <% end %>
	            </li>
	          </ul>
	        </li>
	        <% if current_page?(admin_bundles_path) or current_page?(new_admin_bundle_path) %>
	          <li class="active">
	        <%else%>
	          <li class="">
	        <%end%>
	          <a href="#">
		          <i class="fa fa-circle-o"></i>
		          <span>Paquetes</span>
		          <i class="fa fa-angle-left pull-right"></i>
	          </a>
	          <ul class="treeview-menu menu-open" style="">
	            <% if current_page?(new_admin_bundle_path) %>
	              <li class="active">
	            <%else%>
	              <li class="">
	            <%end%>
	              <%= link_to new_admin_bundle_path do %>
	                <i class="fa fa-circle-o"></i>
	                <span>Nueva</span>
	              <% end %>
	            </li>
	            <% if current_page?(admin_bundles_path) %>
	              <li class="active">
	            <%else%>
	              <li class="">
	            <%end%>
	              <%= link_to admin_bundles_path do %>
	                <i class="fa fa-circle-o"></i>
	                <span>Todos los paquetes</span>
	              <% end %>
	            </li>
	          </ul>
	        </li>
	      </ul>
	    </li>

	    <!-- nav 4 -->
	    <% if current_page?(admin_freelances_path) or current_page?(new_admin_freelance_path) or current_page?(admin_f_roles_path) or current_page?(new_admin_f_role_path) %>
	      <li class="treeview active">
	    <%else%>
	      <li class="treeview">
	    <%end%>
		      <a href="#">
			      <i class="fa fa-link"></i> 
			      <span>Freelances</span>
			      <i class="fa fa-angle-left pull-right"></i>
		      </a>
		      <ul class="treeview-menu menu-open" style="">
		      <% if current_page?(new_admin_freelance_path) %>
		      	<li class="active">
		      <%else%>
		        <li class="">
		      <%end%>
		        <%= link_to new_admin_freelance_path do %>
			        <i class="fa fa-circle-o"></i>
			        <span>Nuevo</span>
		        <% end %>
		        </li>
		        <% if current_page?(admin_freelances_path) %>
		        	<li class="active">
		        <%else%>
		        	<li class="">
		        <%end%>
		        <%= link_to admin_freelances_path do %>
			        <i class="fa fa-circle-o"></i>
			        <span>Todos los freelances</span>
		        <% end %>
		        </li>
		        <% if current_page?(admin_f_roles_path) or current_page?(new_admin_f_role_path) %>
	          	<li class="active">
	        	<%else%>
	          	<li class="">
	        	<%end%>
	          	<a href="#">
		          	<i class="fa fa-circle-o"></i>
		           	<span>Roles</span>
		           	<i class="fa fa-angle-left pull-right"></i>
	          	</a>
	          <ul class="treeview-menu menu-open" style="">
	          	<% if current_page?(new_admin_f_role_path) %>
		      			<li class="active">
		      		<%else%>
		        		<li class="">
		      		<%end%>
		        	<%= link_to new_admin_f_role_path do %>
			        	<i class="fa fa-circle-o"></i>
			        	<span>Nuevo</span>
		        	<% end %>
		        	</li>
		        	<% if current_page?(admin_f_roles_path) %>
		        		<li class="active">
		        	<%else%>
		        		<li class="">
		        	<%end%>
		        	<%= link_to admin_f_roles_path do %>
			        	<i class="fa fa-circle-o"></i>
			        	<span>Todos los roles</span>
		        	<% end %>
		        	</li>
	          </ul>
		      </ul>
	    </li>


	<!-- nav 5 -->
	    <% if current_page?(admin_admins_path) or current_page?(new_admin_admin_path) or current_page?(new_admin_role_path) or current_page?(admin_roles_path)%>
	      <li class="treeview active">
	    <%else%>
	      <li class="treeview">
	    <%end%>
		      <a href="#">
			      <i class="fa fa-link"></i> 
			      <span>Administradores</span>
			      <i class="fa fa-angle-left pull-right"></i>
		      </a>
		      <ul class="treeview-menu menu-open" style="">
		      <% if current_page?(new_admin_admin_path) %>
		      	<li class="active">
		      <%else%>
		        <li class="">
		      <%end%>
		        <%= link_to new_admin_admin_path do %>
			        <i class="fa fa-circle-o"></i>
			        <span>Nuevo</span>
		        <% end %>
		        </li>
		        <% if current_page?(admin_admins_path) %>
		        	<li class="active">
		        <%else%>
		        	<li class="">
		        <%end%>
		        <%= link_to admin_admins_path do %>
			        <i class="fa fa-circle-o"></i>
			        <span>Todos los administradores</span>
		        <% end %>
		        </li>
		        <% if current_page?(new_admin_role_path) or current_page?(admin_roles_path)%>
	          <li class="active">
	        <%else%>
	          <li class="">
	        <%end%>
	          <a href="#">
		          <i class="fa fa-circle-o"></i>
		           <span>Roles</span>
		           <i class="fa fa-angle-left pull-right"></i>
	          </a>
	          <ul class="treeview-menu menu-open" style="">
	          	<% if current_page?(new_admin_role_path) %>
		      			<li class="active">
		      		<%else%>
		        		<li class="">
		      		<%end%>
		        	<%= link_to new_admin_role_path do %>
			        	<i class="fa fa-circle-o"></i>
			        	<span>Nuevo</span>
		        	<% end %>
		        	</li>
		        	<% if current_page?(admin_roles_path) %>
		        		<li class="active">
		        	<%else%>
		        		<li class="">
		        	<%end%>
		        	<%= link_to admin_roles_path do %>
			        	<i class="fa fa-circle-o"></i>
			        	<span>Todos los roles</span>
		        	<% end %>
		        	</li>
	          </ul>
		      </ul>
	    </li>

	    <!-- nav 6 -->
	        <% if current_page?(admin_form_builds_path) or current_page?(new_admin_form_build_path) %>
	          <li class="treeview active">
	        <%else%>
	          <li class="treeview">
	        <%end%>
	    	      <a href="#">
	    		      <i class="fa fa-link"></i> 
	    		      <span>Formularios</span>
	    		      <i class="fa fa-angle-left pull-right"></i>
	    	      </a>
	    	      <ul class="treeview-menu menu-open" style="">
	    	      <% if current_page?(new_admin_form_build_path) %>
	    	      	<li class="active">
	    	      <%else%>
	    	        <li class="">
	    	      <%end%>
	    	        <%= link_to new_admin_form_build_path do %>
	    		        <i class="fa fa-circle-o"></i>
	    		        <span>Nuevo</span>
	    	        <% end %>
	    	        </li>
	    	        <% if current_page?(admin_form_builds_path) %>
	    	        	<li class="active">
	    	        <%else%>
	    	        	<li class="">
	    	        <%end%>
	    	        <%= link_to admin_form_builds_path do %>
	    		        <i class="fa fa-circle-o"></i>
	    		        <span>Todos los formularios</span>
	    	        <% end %>
	    	        </li>
	    	      </ul>
	        </li>


	        <!-- nav 7 -->
	            
	            


	    
	  </ul><!-- /.sidebar-menu -->
	</section>
<!-- /.sidebar -->
</aside>