config/routes.rb
Rails.application.routes.draw do


  root 'home#index'

  mount Ckeditor::Engine => '/ckeditor'

  get 'service/:url' => 'pages#show'
  get 'admin', to: redirect('/administraccion/login')
  get 'freelance', to: redirect('/freelance/login')
  get 'login', to: redirect('/usuario/iniciar_sesion')

  resources :forms, :form_answers, :pages

  devise_for :admins, path: 'administraccion', path_names: {sign_in: 'login', sign_out: 'cerrar_session'}, :skip =>[:registrations], controllers: {
    sessions: 'admins/sessions'
  }
  
  devise_for :users, path: 'usuario', path_names: {sign_in: 'iniciar_sesion', sign_up: 'registrate'}, controllers: {
    sessions: 'users/sessions'
  }

  devise_for :freelances, path: 'freelance', path_names: {sign_in: 'login'}, :skip =>[:registrations], controllers: {
    sessions: 'freelances/sessions'
  }


  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    resources :roles, :f_roles, :services, :pages, :deliveries, :admins, :freelances, :form_builds, :form_questions
    scope '/service' do
      resources :categories, :bundles
    end
  end

  namespace :freelance do
    get 'dashboard' => 'dashboard#index'
  end
 
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :category
  belongs_to :page
  has_many :form_builds
  has_and_belongs_to_many :bundles
  has_many :deliveries
  accepts_nested_attributes_for :deliveries, allow_destroy: true
  
	before_save :capitalize_name
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\Z/
  has_attached_file :imghover, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :imghover, content_type: /\Aimage\/.*\Z/
  #has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "0.png"
  #validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	protected
	def capitalize_name
      self.name = self.name.capitalize
    end
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < ApplicationController
	layout 'admin'
	before_action :authenticate_admin!

	def index
		@services = Service.all.order(created_at: :desc)
		
	end

	def new
		@service = Service.new
		@service.deliveries.build
	end

	def create
	  @service = Service.new(service_params)
	  if @service.save
      redirect_to admin_services_path, notice: t('.created', model: @service.class.model_name.human)
	  else
	    render :new
	  end
	end

	def edit
		@service = Service.find(params[:id])
	end

	def update
		@service = Service.find(params[:id])
	  if @service.update(service_params)
	    redirect_to admin_services_path, notice: t('.created', model: @service.class.model_name.human)
	  else
	    render 'edit'
	  end
	end

	def destroy
	  @service = Service.find(params[:id])
	  @service.deliveries.destroy_all
	  @service.destroy
	  redirect_to admin_services_path, notice: t('.created', model: @service.class.model_name.human)
	end

  private
		def service_params
		  params.require(:service).permit(:name, :category_id, :bundle_id, :img, :imghover, deliveries_attributes: [ :id, :name, :price, :description, :_destroy])
		end
end

app/views/admin/services/_delivery_fields.html.haml
#delivery_form
	= f.text_field :name, placeholder: "Ingrese un nombre"
	= f.text_field :price, placeholder: "0"
	= f.text_field :description, placeholder: "Ingrese una descripción"
	= f.hidden_field :_destroy
	= link_to "Eliminar", '#', class: "remove_fields pull-right"

app/views/admin/services/edit.html.haml
%section.content-wrapper
  %section.content
    .row
      .col-md-12
        .box.box-primary
          .box-header.with-border
            %h3.box-title Editar Servicio
          .box-body
            = form_for [@service], url: {action: "update"}, html:{role: "form", multipart: true} do |f|
              .col-md-9
                .input-field
                  = f.text_field :name, autofocus: true, class: "validate", id: "fName"
                  %label{for: "fName"} Nombre
                .form-group.text-center.clearfix
                  .row
                    %h5 Imagen
                    %hr
                    .col-md-6
                      .picturePreview
                        = image_tag @service.img.url(:thumb)
                    .col-md-6
                      %strong 
                      .picturePreview#target
                      = f.file_field :img, class: "inputFile", id: "pictureInput"
                      %label{for: 'pictureInput'}
                        %span Selecione una imagen
                  .row
                    %h5 Imagen Hover
                    %hr
                    .col-md-6
                      .picturePreview
                        = image_tag @service.imghover.url(:thumb)
                    .col-md-6
                      %strong 
                      .picturePreview#targetHover
                      = f.file_field :imghover, class: "inputFile", id: "pictureInputHover"
                      %label{for: 'pictureInputHover'}
                        %span Selecione una imagen
                .input-field
                  %h5 Categoria
                  = f.collection_select(:category_id, Category.all, :id, :name, {:include_blank => 'Selecione una categoria'}, class: "collection_select", style: "display: block;")
                .input-field
                  %h5 Delivery
                  = f.fields_for :deliveries do |delivery|
                    = render 'delivery_fields', f: delivery
                  = link_to_add_fields "Agregar", f, :deliveries
              .col-md-3
                .input-field
                  %button.waves-effect.btn-block.btn-large.deep-orange.darken-2 Editar
                .imput-field{style: "margin-top: 50px;"}

app/views/admin/services/index.html.haml
%section.content-wrapper
  %section.content-header
    %h1 Todos los servicios
  %section.content
    .row
      .col-xs-12
        .box
          .box-body.table-responsive.no-padding
            %table.table.table-hover
              %tbody
                %tr
                  %th Nombre
                  %th Categoria
                  %th Imagen
                  %th Fecha de creación
                  %th{colspan: "2"} Acciones
              - @services.each do |service|
                %tr
                  %td= service.name 
                  - if !service.category.nil?
                    %td= service.category.name
                  - else
                    %td
                  %td= image_tag service.img.url(:thumb), style: "width: 50%;"
                  %td= service.created_at.httpdate.to_date 
                  %td
                    = link_to edit_admin_service_path(service) do
                      %i.fa.fa-edit
                  %td
                    = link_to admin_service_path(service), method: :delete, data: { confirm: 'Are you sure?' } do
                      %i.fa.fa-remove

app/views/admin/services/new.html.haml
%section.content-wrapper
  %section.content
    .row
      .col-md-12
        .box.box-primary
          .box-header.with-border
            %h3.box-title Nuevo Servicio
          .box-body
            = form_for [@service], url: {action: "create"}, html:{role: "form", multipart: true} do |f|
              .col-md-9
                .input-field
                  = f.text_field :name, {autofocus: true, class: "validate", id: "serviceName"}
                  %label{for: "serviceName"} Nombre
                .row
                  .col-md-6
                    .text-center.clearfix
                      %strong Imagen
                      .picturePreview#target
                      = f.file_field :img, class: "inputFile", id: "pictureInput"
                      %label{for: 'pictureInput'}
                        %span Selecione una imagen
                  .col-md-6
                    .text-center.clearfix
                      %strong Imagen Hover
                      .picturePreview#targetHover
                      = f.file_field :imghover, class: "inputFile", id: "pictureInputHover"
                      %label{for: 'pictureInputHover'}
                        %span Selecione una imagen
                .input-field
                  %h5 Categoria
                  = f.collection_select(:category_id, Category.all, :id, :name, {:include_blank => 'Selecione una categoria'}, class: "collection_select", style: "display: block;")
                .input-field
                  %h5 Delivery
                  = f.fields_for :deliveries do |delivery|
                    = render 'delivery_fields', f: delivery
                  = link_to_add_fields "Agregar", f, :deliveries
              .col-md-3
                .input-field
                  %button.waves-effect.btn-block.btn-large.deep-orange.darken-2 Crear
                .imput-field{style: "margin-top: 50px;"}
                