config/routes.rb
Rails.application.routes.draw do


  root 'home#index'

  mount Ckeditor::Engine => '/ckeditor'

  get 'service/:url' => 'pages#show'
  get 'admin', to: redirect('/administraccion/login')
  get 'freelance', to: redirect('/freelance/login')
  get 'login', to: redirect('/usuario/iniciar_sesion')

  resources :forms, :form_answers, :pages

  devise_for :admins, path: 'administraccion', path_names: {sign_in: 'login', sign_out: 'cerrar_session'}, :skip =>[:registrations], controllers: {
    sessions: 'admins/sessions'
  }
  
  devise_for :users, path: 'usuario', path_names: {sign_in: 'iniciar_sesion', sign_up: 'registrate'}, controllers: {
    sessions: 'users/sessions'
  }

  devise_for :freelances, path: 'freelance', path_names: {sign_in: 'login'}, :skip =>[:registrations], controllers: {
    sessions: 'freelances/sessions'
  }


  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    resources :roles, :f_roles, :services, :pages, :deliveries, :admins, :freelances, :form_builds, :form_questions
    scope '/service' do
      resources :categories, :bundles
    end
  end

  namespace :freelance do
    get 'dashboard' => 'dashboard#index'
  end
 
end

app/models/admin.rb
class Admin < ActiveRecord::Base
	belongs_to :role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", cover: "160x160>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/bundle.rb
class Bundle < ActiveRecord::Base
	has_and_belongs_to_many :services
  belongs_to :page
  before_save :capitalize_name
	 has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\Z/
  has_attached_file :imghover, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :imghover, content_type: /\Aimage\/.*\Z/

	protected
	def capitalize_name
      self.name = self.name.capitalize
    end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :services
	before_save :capitalize_name

	protected
	def capitalize_name
      self.name = self.name.capitalize
    end
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
	belongs_to :service
end

app/models/f_role.rb
class FRole < ActiveRecord::Base
	has_many :freelances
	before_save :capitalize_name

	protected
	def capitalize_name
      self.name = self.name.capitalize
    end
end

app/models/form.rb
class Form < ActiveRecord::Base
  belongs_to :form_build
  belongs_to :status_order
  has_many :answers, class_name: 'FormAnswer'
	accepts_nested_attributes_for :answers, allow_destroy: true

	before_save :status

	protected
	def status
			status_name = StatusOrder.find_by_name('Pendiente')
      self.status_order_id = status_name.id
    end
end

app/models/form_answer.rb
class FormAnswer < ActiveRecord::Base
  belongs_to :form
end

app/models/form_build.rb
class FormBuild < ActiveRecord::Base
	belongs_to :service
	has_many :questions, class_name: 'FormQuestion'
	accepts_nested_attributes_for :questions, allow_destroy: true
end

app/models/form_question.rb
class FormQuestion < ActiveRecord::Base
  belongs_to :form_build
end

app/models/freelance.rb
class Freelance < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable :timeoutable and :omniauthable
  belongs_to :level
  belongs_to :f_role
  after_save :create_wallet
  devise :database_authenticatable, :recoverable, :registerable,
    :rememberable, :trackable, :validatable
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", cover: "160x160>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :gender, :name, :last_name, :f_role_id, presence: true

  def create_wallet
  	id = self.id
  	if !Wallet.find_by_freelance_id(id)
	  	wallet = Wallet.new
	  	wallet.money = 0
	  	wallet.freelance_id = id
		  wallet.save
  	end
  end

end

app/models/level.rb
class Level < ActiveRecord::Base
	has_many :freelances
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :service
  belongs_to :bundle
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :admins
	before_save :capitalize_name

	protected
	def capitalize_name
      self.name = self.name.capitalize
    end
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :category
  belongs_to :page
  has_many :form_builds
  has_and_belongs_to_many :bundles
  has_many :deliveries
  accepts_nested_attributes_for :deliveries, allow_destroy: true
  
	before_save :capitalize_name
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\Z/
  has_attached_file :imghover, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :imghover, content_type: /\Aimage\/.*\Z/
  #has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "0.png"
  #validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	protected
	def capitalize_name
      self.name = self.name.capitalize
    end
end

app/models/status_order.rb
class StatusOrder < ActiveRecord::Base
	has_many :forms
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/wallet.rb
class Wallet < ActiveRecord::Base
	belongs_to :freelance
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < ApplicationController
		layout 'admin'
	before_action :authenticate_admin!
	
	def index
		@roles = Role.all.order(created_at: :desc)
	end

	def new
		@role = Role.new
	end

	def create
	  role = Role.new(roles_params)
	  if role.save
	  	redirect_to admin_roles_path
	    message = "Role creado"
	  else
	    message = "Error al crear el Role"
	  end
	end

	def edit
		@role = Role.find(params[:id])
	end

	def update
		@role = Role.find(params[:id])
	  if @role.update(roles_params)
	    redirect_to admin_roles_path
	  else
	    render 'edit'
	  end
	end

	def destroy
	  @role = Role.find(params[:id])
	  @role.destroy
	  redirect_to admin_roles_path
	end

	def roles_params
	  params.require(:role).permit(:name)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	@pagesServices = Page.where(visibility: true).where.not(service_id: nil)
  	@pagesBundles = Page.where(visibility: true).where.not(bundle_id: nil)

  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def show
		@page = Page.find_by_url(params[:url])
    @form = FormQuestion.where(form_build_id = @page.form_build_id)
		@formDelivery = FormBuild.find_by_id(@page.form_build_id)
		@answer = Form.new
    @answer.answers.build

  end

  def create
    @answer = Form.new(form_params)
    if @answer.save
      redirect_to root_path, notice: 'Survey was successfully created.'
    else
      puts "----------------" + @answer.form_build_id
    end
  end

  private

    def form_params
      params.require(:form).permit(:form_build_id, :status_order_id, answers_attributes: [ :id, :content, :_destroy])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |question|
      render(association.to_s.singularize + "_fields", f: question)
    end
    link_to(name, '', class: "add_fields", data: { id: id, fields: fields.gsub("\n", "")})
  end
end

app/views/admin/roles/edit.html.haml
%section.content-wrapper
  %section.content
    .row
      .col-md-12
        .box.box-primary
          .box-header.with-border
            %h5 Editar Role
          .box-body
            = form_for [@role], url: {action: "update"}, html:{role: "form"} do |f|
              .col-md-9
                .input-field
                  = f.text_field :name, autofocus: true, class: "validate", id: "fName"
                  %label{for: "fName"} Nombre
              .col-md-3
                .input-field
                  %button.waves-effect.btn-block.btn-large.deep-orange.darken-2 Editar
                .imput-field{style: "margin-top: 50px;"}

app/views/admin/roles/index.html.haml
%section.content-wrapper
  %section.content-header
    %h1 Roles
  %section.content
    .row
      .col-xs-12
        .box
          .box-header
            %h5
          .box-body.table-responsive.no-padding
            %table.table.table-hover
              %tbody
                %tr
                  %th Nombre
                  %th Fecha de creación
                  %th{colspan: "2"} Acciones
              - @roles.each do |role|
                %tr
                  %td= role.name
                  %td= role.created_at.httpdate.to_date
                  %td 
                    = link_to edit_admin_role_path(role) do
                      %i.fa.fa-edit
                  %td
                    = link_to admin_role_path(role), method: :delete, data: { confirm: 'Esta seguro?' } do
                      %i.fa.fa-remove{style: "color: #B21919;"}

app/views/admin/roles/new.html.haml
%section.content-wrapper
  %section.content
    .row
      .col-md-12
        .box.box-primary
          .box-header.with-border
            %h5 Nuevo Role
          .box-body
            = form_for [@role], url: {action: "create"}, html:{role: "form"} do |f|
              .col-md-9
                .input-field
                  = f.text_field :name, autofocus: true, class: "validate", id: "fName"
                  %label{for: "fName"} Nombre
              .col-md-3
                .input-field
                  %button.waves-effect.btn-block.btn-large.deep-orange.darken-2 Crear
                .imput-field{style: "margin-top: 50px;"}